import type { CustomerPortalData, CreateCheckoutResponse } from '../../src/client/types'

export const mockPortalData: CustomerPortalData = {
  subscription: {
    id: 'sub_demo123',
    status: 'active',
    product: {
      id: 'prod_pro',
      name: 'Pro Plan',
      description: 'Best for growing teams',
    },
    price: {
      id: 'price_pro_monthly',
      amount: 4900,
      currency: 'usd',
      interval: 'month',
      intervalCount: 1,
    },
    currentPeriodStart: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    currentPeriodEnd: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    cancelAtPeriodEnd: false,
    trialEnd: null,
    canceledAt: null,
    features: [
      {
        id: 'feature_api_calls',
        name: 'api_calls',
        title: 'API Calls',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 7500,
          limit: 10000,
          percentage: 75,
          resetDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
      },
      {
        id: 'feature_storage',
        name: 'storage',
        title: 'Storage',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 3,
          limit: 10,
          percentage: 30,
          resetDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
      },
      {
        id: 'feature_team_members',
        name: 'team_members',
        title: 'Team Members',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 4,
          limit: 10,
          percentage: 40,
        },
      },
      {
        id: 'feature_projects',
        name: 'projects',
        title: 'Projects',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 8,
          limit: 25,
          percentage: 32,
        },
      },
      {
        id: 'feature_webhooks',
        name: 'webhooks',
        title: 'Webhook Endpoints',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 12,
          limit: 50,
          percentage: 24,
        },
      },
      {
        id: 'feature_api_rate_limit',
        name: 'api_rate_limit',
        title: 'API Rate Limit',
        type: 'usage_quota',
        properties: {},
        usage: {
          consumed: 850,
          limit: 1000,
          percentage: 85,
        },
      },
      {
        id: 'feature_support',
        name: 'priority_support',
        title: 'Priority Support',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
      {
        id: 'feature_branding',
        name: 'custom_branding',
        title: 'Custom Branding',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
      {
        id: 'feature_analytics',
        name: 'advanced_analytics',
        title: 'Advanced Analytics',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
      {
        id: 'feature_sso',
        name: 'sso_integration',
        title: 'SSO Integration',
        type: 'boolean_flag',
        properties: {},
        enabled: false,
      },
      {
        id: 'feature_backup',
        name: 'automated_backup',
        title: 'Automated Backups',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
      {
        id: 'feature_team_members',
        name: 'team_members',
        title: 'Team Members',
        type: 'numeric_limit',
        properties: {},
        usage: {
          consumed: 4,
          limit: 10,
          percentage: 40,
        },
      },
      {
        id: 'feature_priority_support',
        name: 'priority_support',
        title: 'Priority Support',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
      {
        id: 'feature_custom_branding',
        name: 'custom_branding',
        title: 'Custom Branding',
        type: 'boolean_flag',
        properties: {},
        enabled: true,
      },
    ],
  },
  invoices: [
    {
      id: 'inv_001',
      number: 'INV-2024-001',
      date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_002',
      number: 'INV-2024-002',
      date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_003',
      number: 'INV-2024-003',
      date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'open',
      amount: 4900,
      currency: 'usd',
      pdfUrl: null,
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_004',
      number: 'INV-2024-004',
      date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_005',
      number: 'INV-2024-005',
      date: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 105 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_006',
      number: 'INV-2024-006',
      date: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 135 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'failed',
      amount: 4900,
      currency: 'usd',
      pdfUrl: null,
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
      failureReason: 'Your card was declined.',
    },
    {
      id: 'inv_007',
      number: 'INV-2024-007',
      date: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 165 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
    {
      id: 'inv_008',
      number: 'INV-2024-008',
      date: new Date(Date.now() - 210 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() - 195 * 24 * 60 * 60 * 1000).toISOString(),
      status: 'paid',
      amount: 4900,
      currency: 'usd',
      pdfUrl: '#',
      lineItems: [
        { description: 'Pro Plan - Monthly', quantity: 1, amount: 4900 },
      ],
    },
  ],
  paymentMethods: [
    {
      id: 'pm_visa',
      type: 'card',
      card: {
        brand: 'visa',
        last4: '4242',
        expMonth: 12,
        expYear: 2026,
      },
      isDefault: true,
    },
    {
      id: 'pm_mastercard',
      type: 'card',
      card: {
        brand: 'mastercard',
        last4: '8888',
        expMonth: 6,
        expYear: 2025,
      },
      isDefault: false,
    },
  ],
  customer: {
    id: 'cust_demo123',
    email: 'demo@example.com',
    name: 'Demo User',
    billingAddress: {
      line1: '123 Demo Street',
      line2: 'Suite 100',
      city: 'San Francisco',
      state: 'CA',
      postalCode: '94105',
      country: 'US',
    },
  },
  availablePlans: [
    {
      id: 'price_starter_monthly',
      name: 'Starter',
      price: {
        amount: 1900,
        currency: 'usd',
        interval: 'month',
      },
      type: 'downgrade',
    },
    {
      id: 'price_pro_monthly',
      name: 'Pro',
      price: {
        amount: 4900,
        currency: 'usd',
        interval: 'month',
      },
      type: 'current',
    },
    {
      id: 'price_enterprise_monthly',
      name: 'Enterprise',
      price: {
        amount: 9900,
        currency: 'usd',
        interval: 'month',
      },
      type: 'upgrade',
    },
  ],
}

// Mock checkout session data for PaymentBottomSheet
export const mockCheckoutSession: CreateCheckoutResponse = {
  checkoutSession: {
    id: 'cs_test_demo123',
    clientSecret: 'cs_test_demo123_secret_xyz789',
    amount: 9900,
    currency: 'usd',
    product: {
      name: 'Enterprise',
      interval: 'month',
      features: [
        'Unlimited API calls',
        '24/7 Priority support',
        'Advanced analytics dashboard',
        'Custom integrations',
        'Dedicated account manager',
      ],
    },
    customer: {
      email: 'demo@example.com',
      name: 'Demo User',
    },
    stripePublishableKey: 'pk_test_demo',
    stripeAccountId: 'acct_demo123',
  },
}

// Mock checkout session with proration (for upgrades)
export const mockCheckoutSessionWithProration: CreateCheckoutResponse = {
  checkoutSession: {
    id: 'cs_test_upgrade123',
    clientSecret: 'cs_test_upgrade123_secret_xyz789',
    amount: 9900,
    currency: 'usd',
    proration: {
      credited: 2450, // Credit for unused Pro plan time
      charged: 9900,
      total: 7450,
      explanation: "You'll be credited $24.50 for the unused portion of your Pro plan.",
    },
    product: {
      name: 'Enterprise',
      interval: 'month',
      features: [
        'Unlimited API calls (was 10,000)',
        'Unlimited projects (was 25)',
        'Dedicated account manager',
        '99.9% SLA guarantee',
      ],
    },
    customer: {
      email: 'demo@example.com',
      name: 'Demo User',
    },
    stripePublishableKey: 'pk_test_demo',
    stripeAccountId: 'acct_demo123',
  },
}
